# **Policy Tracker América Latina**

##1 - Importando pacotes

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

##2 - Extraindo dados

Tabela de medidas de contenção

In [ ]:
df_LAT = pd.read_csv('https://github.com/OxCGRT/covid-policy-tracker-legacy/blob/main/legacy_data_202207/OxCGRT_latest.csv?raw=true', low_memory = False)
df_LAT.head()

,CountryName,CountryCode,RegionName,RegionCode,Jurisdiction,Date,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
0,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200101,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200102,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200103,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200104,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200105,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Pegando apenas dados a nível nacional

In [ ]:
df_LAT = df_LAT[df_LAT['Jurisdiction' ]=='NAT_TOTAL']

Diabetes prevalence

In [ ]:
df_diabetes = pd.read_excel('https://api.worldbank.org/v2/en/indicator/SH.STA.DIAB.ZS?downloadformat=excel', sheet_name="Data", header = 3)
df_diabetes.head(5)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Aruba,ABW,Diabetes prevalence (% of population ages 20 t...,SH.STA.DIAB.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.300000,NaN
1,Africa Eastern and Southern,AFE,Diabetes prevalence (% of population ages 20 t...,SH.STA.DIAB.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.381941,NaN
2,Afghanistan,AFG,Diabetes prevalence (% of population ages 20 t...,SH.STA.DIAB.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.900000,NaN
3,Africa Western and Central,AFW,Diabetes prevalence (% of population ages 20 t...,SH.STA.DIAB.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.389805,NaN
4,Angola,AGO,Diabetes prevalence (% of population ages 20 t...,SH.STA.DIAB.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.600000,NaN

In [ ]:
df_diabetes = df_diabetes[['Country Name', 'Country Code', '2021']]
df_diabetes.rename(columns={str(2021):'Diabetes_Prevalence_2021'}, inplace=True)
df_diabetes.head(5)

<ipython-input-5-5c524030d39f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_diabetes.rename(columns={str(2021):'Diabetes_Prevalence_2021'}, inplace=True)

                  Country Name Country Code  Diabetes_Prevalence_2021
0                        Aruba          ABW                  4.300000
1  Africa Eastern and Southern          AFE                  7.381941
2                  Afghanistan          AFG                 10.900000
3   Africa Western and Central          AFW                  3.389805
4                       Angola          AGO                  4.600000

Tabela trabalho informal

In [ ]:
df_trabalho_informal = pd.read_excel('/content/TB_trabalho_informal.xlsx')
df_trabalho_informal.head(5)

,ref_area.label,indicator.label,source.label,sex.label,classif1.label,time,obs_value
0,Afghanistan,SDG indicator 8.3.1 - Proportion of informal e...,LFS - Labour Force Survey,Sex: Total,"Economic activity (Agriculture, Non-Agricultur...",2021,86.4
1,Afghanistan,SDG indicator 8.3.1 - Proportion of informal e...,LFS - Labour Force Survey,Sex: Total,"Economic activity (Agriculture, Non-Agricultur...",2021,98.4
2,Afghanistan,SDG indicator 8.3.1 - Proportion of informal e...,LFS - Labour Force Survey,Sex: Total,"Economic activity (Agriculture, Non-Agricultur...",2021,82.4
3,Angola,SDG indicator 8.3.1 - Proportion of informal e...,HIES - Core Welfare Indicators Questionnaire,Sex: Total,"Economic activity (Agriculture, Non-Agricultur...",2011,84.3
4,Angola,SDG indicator 8.3.1 - Proportion of informal e...,HIES - Core Welfare Indicators Questionnaire,Sex: Total,"Economic activity (Agriculture, Non-Agricultur...",2011,99.8

In [ ]:
df_trabalho_informal_ag = df_trabalho_informal[df_trabalho_informal['classif1.label']=='Economic activity (Agriculture, Non-Agriculture): Agriculture']
df_trabalho_informal_ag = df_trabalho_informal_ag[['ref_area.label', 'obs_value']]
df_trabalho_informal_ag.rename(columns={'obs_value':'pct_informal_ag_jobs'}, inplace=True)
df_trabalho_informal_nag = df_trabalho_informal[df_trabalho_informal['classif1.label']=='Economic activity (Agriculture, Non-Agriculture): Non-agriculture']
df_trabalho_informal_nag = df_trabalho_informal_nag[['ref_area.label', 'obs_value']]
df_trabalho_informal_nag.rename(columns={'obs_value':'pct_informal_n_ag_jobs'}, inplace=True)
df_trabalho_informal_tot = df_trabalho_informal[df_trabalho_informal['classif1.label']=='Economic activity (Agriculture, Non-Agriculture): Total']
df_trabalho_informal_tot = df_trabalho_informal_tot[['ref_area.label', 'obs_value']]
df_trabalho_informal_tot.rename(columns={'obs_value':'pct_informal_tot_jobs'}, inplace=True)
df_trabalho_informal_mod = pd.merge(df_trabalho_informal_ag, df_trabalho_informal_nag, on ='ref_area.label' , how='inner')
df_trabalho_informal_mod = pd.merge(df_trabalho_informal_mod, df_trabalho_informal_tot, on ='ref_area.label' , how='inner')
df_trabalho_informal_mod.head(5)

,ref_area.label,pct_informal_ag_jobs,pct_informal_n_ag_jobs,pct_informal_tot_jobs
0,Afghanistan,98.4,82.4,86.4
1,Angola,99.8,68.1,84.3
2,Albania,99.4,32.2,56.7
3,Argentina,28.8,49.0,48.9
4,Armenia,76.0,19.9,49.3

Tabela hospitais por 100 mil pessoas *****dados de 2013

In [ ]:
df_hospital_density = pd.read_excel('/content/TB_hospital_per_hab.xlsx')
df_hospital_density_mod = df_hospital_density[['Location', 'SpatialDimValueCode', 'Period', 'Value', 'FactComments']]
df_hospital_density.head(5)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,DEVICES00,Total density per 100 000 population: Hospitals,numeric,WPR,Western Pacific,Country,TUV,Tuvalu,Year,2014,...,NaN,NaN,NaN,NaN,NaN,0.016,NaN,Only public sector data,EN,2016-01-28T02:00:00.000Z
1,DEVICES00,Total density per 100 000 population: Hospitals,numeric,EUR,Europe,Country,MKD,The former Yugoslav Republic of Macedonia,Year,2014,...,NaN,NaN,NaN,NaN,NaN,4.080,NaN,NaN,EN,2016-01-28T02:00:00.000Z
2,DEVICES00,Total density per 100 000 population: Hospitals,numeric,WPR,Western Pacific,Country,FJI,Fiji,Year,2013,...,NaN,NaN,NaN,NaN,NaN,0.000,NaN,Both public sector data and private sector data,EN,2015-03-31T03:00:00.000Z
3,DEVICES00,Total density per 100 000 population: Hospitals,numeric,WPR,Western Pacific,Country,KIR,Kiribati,Year,2013,...,NaN,NaN,NaN,NaN,NaN,0.000,NaN,Both public sector data and private sector data,EN,2015-03-31T03:00:00.000Z
4,DEVICES00,Total density per 100 000 population: Hospitals,numeric,AMR,Americas,Country,VCT,Saint Vincent and the Grenadines,Year,2013,...,NaN,NaN,NaN,NaN,NaN,0.000,NaN,Both public sector data and private sector data,EN,2015-03-31T03:00:00.000Z

In [ ]:
celula = df_hospital_density_mod.loc[df_hospital_density_mod['Location'] == 'Bolivia (Plurinational State of)'].index
#df_hospital_density_mod.at[celula[0], 'Location'] = 'Bolivia'
df_hospital_density_mod = df_hospital_density_mod[df_hospital_density_mod['Period']==2013]
df_hospital_density_mod.rename(columns={'Value':'Hospital_Density_Per_100k'}, inplace=True)
df_hospital_density_mod = df_hospital_density_mod[['Location', 'Hospital_Density_Per_100k' ]]
df_hospital_density_mod.tail(5)

<ipython-input-13-f32e4fff316d>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_hospital_density_mod.rename(columns={'Value':'Hospital_Density_Per_100k'}, inplace=True)

                  Location  Hospital_Density_Per_100k
132  Saint Kitts and Nevis                       7.38
133                Belarus                       7.45
134                 Cyprus                       7.54
135             Azerbaijan                       7.97
136                  Nauru                       9.95

Population density

In [ ]:
df_density = pd.read_excel('https://api.worldbank.org/v2/en/indicator/EN.POP.DNST?downloadformat=excel', header = 3)
df_density_mod = df_density[['Country Name', 'Country Code', '2020']]
df_density_mod.rename(columns={str(2020):'Population Density'}, inplace=True)
df_density_mod.head(5)

<ipython-input-14-d61672e03c9e>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_density_mod.rename(columns={str(2020):'Population Density'}, inplace=True)

                  Country Name Country Code  Population Density
0                        Aruba          ABW          592.138889
1  Africa Eastern and Southern          AFE           46.150711
2                  Afghanistan          AFG           59.752281
3   Africa Western and Central          AFW           51.536679
4                       Angola          AGO           26.813577

Tabela household size

In [ ]:
df_hhSize = pd.read_excel('/content/TB_hh_size.xlsx', sheet_name='HH size and composition 2022', header = 4)
df_hhSize.head(3)

,Country or area,ISO Code,Data source category,Reference date (dd/mm/yyyy),Average household size (number of members),1 member,2-3 members,4-5 members,6 or more members,Female head of household (percentage of households),...,Single father with children,Extended family,Non-relatives,Unknown,Nuclear,Multi-generation,Three generation,Skip generation,Unnamed: 43,Unnamed: 44
0,Afghanistan,4,MICS,2010-01-07 00:00:00,7.75,0.15,7.41,18.59,73.85,0.86,...,0.27,42.05,0.16,0.04,57.59,47.71,27.28,0.04,NaN,NaN
1,Afghanistan,4,DHS,19/10/2015,8.04,0.19,6.45,16.84,76.52,1.67,...,0.21,46.86,0.19,0,52.77,50.39,32.18,0.07,NaN,NaN
2,Albania,8,MICS,2000-01-07 00:00:00,4.35,4.42,25.59,47.28,22.71,..,...,..,..,..,..,..,..,..,..,NaN,NaN

In [ ]:
from numpy import datetime64
df_hhSize['Reference date (dd/mm/yyyy)'] = df_hhSize['Reference date (dd/mm/yyyy)'].astype(datetime64)

<ipython-input-16-0fef8b05b53a>:2: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df_hhSize['Reference date (dd/mm/yyyy)'] = df_hhSize['Reference date (dd/mm/yyyy)'].astype(datetime64)

In [ ]:
idx = df_hhSize.groupby('Country or area')['Reference date (dd/mm/yyyy)'].idxmax()
df_hhSize = df_hhSize.loc[idx]
df_hhSize = df_hhSize[['Country or area','Average household size (number of members)']]
df_hhSize.head(5)

   Country or area Average household size (number of members)
1      Afghanistan                                       8.04
6          Albania                                        3.3
8          Algeria                                       4.94
12          Angola                                       4.82
19       Argentina                                       2.95

In [ ]:
celula1_hh = df_hhSize.loc[df_hhSize['Country or area'] == 'Bolivia (Plurinational State of)'].index
df_hhSize[ df_hhSize['Country or area'] == 'Bolivia']
celula2_hh = df_hhSize.loc[df_hhSize['Country or area'] == 'Venezuela (Bolivarian Republic of)'].index
#df_hhSize.at[celula2_hh[0], 'Country or area'] = 'Venezuela'

Tabela de IDH

In [ ]:
df_IDH = pd.read_csv('https://hdr.undp.org/sites/default/files/2021-22_HDR/HDR21-22_Composite_indices_complete_time_series.csv', sep=',')

HTTPError: ignored

Deu erro ao tentar puxar usando o pd.read_csv. Abaixo outro jeito de puxar:

In [ ]:



url = "https://hdr.undp.org/sites/default/files/2021-22_HDR/HDR21-22_Composite_indices_complete_time_series.csv"
storage_options = {'User-Agent': 'Mozilla/5.0'}
df_IDH = pd.read_csv(url, storage_options=storage_options)

Tabela de indice de gini

In [ ]:
df_Gini= pd.read_excel('https://api.worldbank.org/v2/en/indicator/SI.POV.GINI?downloadformat=excel', header=3)
df_Gini = df_Gini[df_Gini['Indicator Name']=='Gini index']
#fazer um for
df_Gini.rename(columns=({'2020': 'Gini_2020','2021': 'Gini_2021', '2022': 'Gini_2022'}), inplace=True)
df_Gini.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,Gini_2020,Gini_2021,Gini_2022
0,Aruba,ABW,Gini index,SI.POV.GINI,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,Gini index,SI.POV.GINI,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,Gini index,SI.POV.GINI,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Africa Western and Central,AFW,Gini index,SI.POV.GINI,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,AGO,Gini index,SI.POV.GINI,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,51.3,NaN,NaN,NaN,NaN

Tabela PIB per capita

In [ ]:
df_PIB= pd.read_excel('https://api.worldbank.org/v2/en/indicator/NY.GDP.PCAP.CD?downloadformat=excel', header=3)
df_PIB= df_PIB[df_PIB['Indicator Name']=='GDP per capita (current US$)']
#fazer um for aqui também
df_PIB.rename(columns=({'2020': 'PIB_2020','2021': 'PIB_2021'}), inplace=True)
df_PIB.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,PIB_2020,PIB_2021,2022
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,26515.678080,26942.307976,28421.386493,28451.273745,29326.708058,30918.515218,31902.762582,24487.863569,29342.100730,NaN
1,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,161.638982,161.111657,170.538537,198.038919,178.019217,196.818756,...,1736.222507,1724.534381,1545.559084,1436.094404,1613.668488,1550.111762,1499.954437,1353.927527,1539.165543,1622.391720
2,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,62.369375,62.443703,60.950364,82.021738,85.511073,105.243196,...,651.987862,628.146804,592.476165,520.251955,530.149863,502.057099,500.522981,516.866797,363.674087,NaN
3,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,107.423775,112.503866,118.197351,122.774120,131.163760,137.809818,...,2153.766138,2247.857492,1880.750778,1646.972399,1588.581005,1732.816544,1810.538006,1686.997899,1765.965307,1790.348800
4,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,5101.983876,5059.080441,3100.830685,1709.515534,2283.214233,2487.500996,2142.238757,1502.950754,1903.717405,2998.501158

Redimensionando as tabelas com indicadores socioeconomicos

In [ ]:
#2020
df_socio_economic_2020 = pd.merge(df_IDH[['iso3', 'hdi_2020', 'le_2020',  'eys_2020', 'mys_2020', 'gnipc_2020']], df_PIB[['Country Code','PIB_2020']], left_on=['iso3'], right_on =['Country Code'], how='outer')
df_socio_economic_2020 = pd.merge(df_socio_economic_2020, df_Gini[['Country Name', 'Country Code','Gini_2020']], left_on=['Country Code'], right_on =['Country Code'], how='left')
df_socio_economic_2020['Country Name'] = df_socio_economic_2020.apply(lambda x: 'Venezuela' if x['Country Name'] == 'Venezuela, RB' else x['Country Name'], axis=1)  #Corrigindo nome da Venezuela
df_socio_economic_2020.drop(["iso3"], axis=1, inplace=True)
df_socio_economic_2020['Year'] = 2020
#df_socio_economic_2020['Ind'] = df_socio_economic_2020.index  + 276**1


#2021
df_socio_economic_2021 = pd.merge(df_IDH[['iso3', 'hdi_2021', 'le_2021',  'eys_2021', 'mys_2021', 'gnipc_2021']], df_PIB[['Country Code', 'PIB_2021']], left_on=['iso3'], right_on =['Country Code'], how='outer')
df_socio_economic_2021 = pd.merge(df_socio_economic_2021, df_Gini[['Country Name', 'Country Code','Gini_2021']], left_on=['Country Code'], right_on =['Country Code'], how='left')
df_socio_economic_2021['Country Name'] = df_socio_economic_2021.apply(lambda x: 'Venezuela' if x['Country Name'] == 'Venezuela, RB' else x['Country Name'], axis=1)  #Corrigindo nome da Venezuela
df_socio_economic_2021.drop(["iso3"], axis=1, inplace=True)
df_socio_economic_2021['Year'] = 2021
#df_socio_economic_2021['Ind'] = df_socio_economic_2021.index  + 276**2
df_socio_economic_2021.head()

,hdi_2021,le_2021,eys_2021,mys_2021,gnipc_2021,Country Code,PIB_2021,Country Name,Gini_2021,Year
0,0.478,61.9824,10.263844,2.985070,1824.190915,AFG,363.674087,Afghanistan,NaN,2021
1,0.586,61.6434,12.172100,5.417391,5465.617791,AGO,1903.717405,Angola,NaN,2021
2,0.796,76.4626,14.448000,11.286455,14131.110390,ALB,6377.203096,Albania,NaN,2021
3,0.858,80.3684,13.300239,10.555120,51166.626610,AND,42072.341103,Andorra,NaN,2021
4,0.911,78.7104,15.717690,12.694030,62573.591810,ARE,44315.554184,United Arab Emirates,NaN,2021

In [ ]:
df_socio_economic_2020.rename(columns=({'hdi_2020': 'hdi','le_2020': 'le','eys_2020': 'eys', 'mys_2020': 'mys', 'gnipc_2020': 'gnipc','PIB_2020': 'PIB', 'Gini_2020': 'Gini'}), inplace=True)
df_socio_economic_2021.rename(columns=({'hdi_2021': 'hdi','le_2021': 'le','eys_2021': 'eys', 'mys_2021': 'mys', 'gnipc_2021': 'gnipc','PIB_2021': 'PIB', 'Gini_2021': 'Gini'}), inplace=True)

In [ ]:
df_socio_economic_2021.columns

Index(['hdi', 'le', 'eys', 'mys', 'gnipc', 'Country Code', 'PIB',
       'Country Name', 'Gini', 'Year'],
      dtype='object')

In [ ]:
#juntando anos
df_socio_economic = pd.concat([df_socio_economic_2020, df_socio_economic_2021], axis=0)
df_socio_economic.head()

,hdi,le,eys,mys,gnipc,Country Code,PIB,Country Name,Gini,Year
0,0.483,62.5751,10.263844,2.854718,1997.852149,AFG,516.866797,Afghanistan,NaN,2020
1,0.590,62.2612,12.172100,5.417391,5593.142060,AGO,1502.950754,Angola,NaN,2020
2,0.794,76.9893,14.448000,11.286455,12996.762910,ALB,5343.037704,Albania,29.4,2020
3,0.848,79.0234,13.300239,10.555120,47878.666640,AND,37207.222000,Andorra,NaN,2020
4,0.912,78.9457,15.717690,12.694030,63016.401220,ARE,37629.174168,United Arab Emirates,NaN,2020

Tabela de Vacinação

In [ ]:
df_Vacinacao = pd.read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv", sep=',')
df_Vacinacao.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 334172 entries, 0 to 334171
Data columns (total 67 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    334172 non-null  object
 1   continent                                   318308 non-null  object
 2   location                                    334172 non-null  object
 3   date                                        334172 non-null  object
 4   total_cases                                 296716 non-null  float64
 5   new_cases                                   325119 non-null  float64
 6   new_cases_smoothed                          323860 non-null  float64
 7   total_deaths                                275507 non-null  float64
 8   new_deaths                                  325173 non-null  float64
 9   new_deaths_smoothed                         323943 non-null  float64
 10  total_cases_per_million                     296716 non-null  float64
 11  new_cases_per_million                       325119 non-null  float64
 12  new_cases_smoothed_per_million              323860 non-null  float64
 13  total_deaths_per_million                    275507 non-null  float64
 14  new_deaths_per_million                      325173 non-null  float64
 15  new_deaths_smoothed_per_million             323943 non-null  float64
 16  reproduction_rate                           184817 non-null  float64
 17  icu_patients                                34441 non-null   float64
 18  icu_patients_per_million                    34441 non-null   float64
 19  hosp_patients                               36063 non-null   float64
 20  hosp_patients_per_million                   36063 non-null   float64
 21  weekly_icu_admissions                       9943 non-null    float64
 22  weekly_icu_admissions_per_million           9943 non-null    float64
 23  weekly_hosp_admissions                      22732 non-null   float64
 24  weekly_hosp_admissions_per_million          22732 non-null   float64
 25  total_tests                                 79387 non-null   float64
 26  new_tests                                   75403 non-null   float64
 27  total_tests_per_thousand                    79387 non-null   float64
 28  new_tests_per_thousand                      75403 non-null   float64
 29  new_tests_smoothed                          103965 non-null  float64
 30  new_tests_smoothed_per_thousand             103965 non-null  float64
 31  positive_rate                               95927 non-null   float64
 32  tests_per_case                              94348 non-null   float64
 33  tests_units                                 106788 non-null  object
 34  total_vaccinations                          77691 non-null   float64
 35  people_vaccinated                           74394 non-null   float64
 36  people_fully_vaccinated                     70956 non-null   float64
 37  total_boosters                              46071 non-null   float64
 38  new_vaccinations                            63972 non-null   float64
 39  new_vaccinations_smoothed                   175575 non-null  float64
 40  total_vaccinations_per_hundred              77691 non-null   float64
 41  people_vaccinated_per_hundred               74394 non-null   float64
 42  people_fully_vaccinated_per_hundred         70956 non-null   float64
 43  total_boosters_per_hundred                  46071 non-null   float64
 44  new_vaccinations_smoothed_per_million       175575 non-null  float64
 45  new_people_vaccinated_smoothed              175387 non-null  float64
 46  new_people_vaccinated_smoothed_per_hundred  175387 non-null  float64
 47  stringency_index                            197651 non-null  float64
 48  population_density                          283662 non-null  float64
 49  median_age                                  263789 non-null  float64
 50  aged_65_older                               254578 non-null  float64
 51  aged_70_older                               261145 non-null  float64
 52  gdp_per_capita                              258544 non-null  float64
 53  extreme_poverty                             166577 non-null  float64
 54  cardiovasc_death_rate                       259074 non-null  float64
 55  diabetes_prevalence                         272291 non-null  float64
 56  female_smokers                              194340 non-null  float64
 57  male_smokers                                191696 non-null  float64
 58  handwashing_facilities                      126914 non-null  float64
 59  hospital_beds_per_thousand                  228712 non-null  float64
 60  life_expectancy                             307415 non-null  float64
 61  human_development_index                     251139 non-null  float64
 62  population                                  334172 non-null  float64
 63  excess_mortality_cumulative_absolute        11535 non-null   float64
 64  excess_mortality_cumulative                 11535 non-null   float64
 65  excess_mortality                            11535 non-null   float64
 66  excess_mortality_cumulative_per_million     11535 non-null   float64
dtypes: float64(62), object(5)
memory usage: 170.8+ MB

Redimensionando Tabela de vacinação

In [ ]:
df_Vacinacao_mod = df_Vacinacao[['date', 'location', 'new_cases','total_tests','new_deaths','new_tests','median_age','aged_65_older','aged_70_older','population','human_development_index','life_expectancy','gdp_per_capita','extreme_poverty','hospital_beds_per_thousand','total_vaccinations', 'people_vaccinated' , 'people_fully_vaccinated', 'total_boosters','new_vaccinations','new_vaccinations_smoothed','total_vaccinations_per_hundred', 'people_vaccinated_per_hundred', 'total_boosters_per_hundred', 'new_vaccinations_smoothed_per_million', 'new_people_vaccinated_smoothed_per_hundred' ]]
#Mudando nome da coluna pra ficar igual a tabela de oxford
df_Vacinacao_mod.rename(columns={'date': 'Date'}, inplace = True)
df_Vacinacao_mod.head()

<ipython-input-30-1914e86c4325>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_Vacinacao_mod.rename(columns={'date': 'Date'}, inplace = True)

,Date,location,new_cases,total_tests,new_deaths,new_tests,median_age,aged_65_older,aged_70_older,population,...,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,new_vaccinations_smoothed,total_vaccinations_per_hundred,people_vaccinated_per_hundred,total_boosters_per_hundred,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed_per_hundred
0,2020-01-03,Afghanistan,0.0,NaN,0.0,NaN,18.6,2.581,1.337,41128772.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-01-04,Afghanistan,0.0,NaN,0.0,NaN,18.6,2.581,1.337,41128772.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-01-05,Afghanistan,0.0,NaN,0.0,NaN,18.6,2.581,1.337,41128772.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-01-06,Afghanistan,0.0,NaN,0.0,NaN,18.6,2.581,1.337,41128772.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-01-07,Afghanistan,0.0,NaN,0.0,NaN,18.6,2.581,1.337,41128772.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Tabela mobilidade

In [ ]:
df_mobility = pd.read_csv("https://www.gstatic.com/covid19/mobility/Global_Mobility_Report.csv", sep=',')
df_mobility[df_mobility['country_region']=='Venezuela']

<ipython-input-31-1502806c970d>:1: DtypeWarning: Columns (3,4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mobility = pd.read_csv("https://www.gstatic.com/covid19/mobility/Global_Mobility_Report.csv", sep=',')

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
11636737,VE,Venezuela,NaN,NaN,NaN,NaN,NaN,ChIJAdjLNstTKIwR003VfFjyoNw,2020-02-15,8.0,2.0,3.0,2.0,5.0,-1.0
11636738,VE,Venezuela,NaN,NaN,NaN,NaN,NaN,ChIJAdjLNstTKIwR003VfFjyoNw,2020-02-16,5.0,2.0,1.0,1.0,3.0,0.0
11636739,VE,Venezuela,NaN,NaN,NaN,NaN,NaN,ChIJAdjLNstTKIwR003VfFjyoNw,2020-02-17,6.0,3.0,4.0,3.0,10.0,-1.0
11636740,VE,Venezuela,NaN,NaN,NaN,NaN,NaN,ChIJAdjLNstTKIwR003VfFjyoNw,2020-02-18,3.0,0.0,0.0,1.0,6.0,-1.0
11636741,VE,Venezuela,NaN,NaN,NaN,NaN,NaN,ChIJAdjLNstTKIwR003VfFjyoNw,2020-02-19,5.0,0.0,4.0,4.0,5.0,-3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11637706,VE,Venezuela,NaN,NaN,NaN,NaN,NaN,ChIJAdjLNstTKIwR003VfFjyoNw,2022-10-11,52.0,86.0,53.0,-2.0,41.0,10.0
11637707,VE,Venezuela,NaN,NaN,NaN,NaN,NaN,ChIJAdjLNstTKIwR003VfFjyoNw,2022-10-12,33.0,66.0,41.0,-18.0,-9.0,21.0
11637708,VE,Venezuela,NaN,NaN,NaN,NaN,NaN,ChIJAdjLNstTKIwR003VfFjyoNw,2022-10-13,47.0,77.0,47.0,-4.0,44.0,11.0
11637709,VE,Venezuela,NaN,NaN,NaN,NaN,NaN,ChIJAdjLNstTKIwR003VfFjyoNw,2022-10-14,53.0,85.0,51.0,-2.0,53.0,10.0
11637710,VE,Venezuela,NaN,NaN,NaN,NaN,NaN,ChIJAdjLNstTKIwR003VfFjyoNw,2022-10-15,70.0,101.0,51.0,7.0,70.0,10.0

Redimensionando a tabela de mobilidade

In [ ]:
df_mobility_mod = df_mobility[['date', 'country_region', 'sub_region_1', 'metro_area', 'retail_and_recreation_percent_change_from_baseline' , 'grocery_and_pharmacy_percent_change_from_baseline', 'parks_percent_change_from_baseline','transit_stations_percent_change_from_baseline','workplaces_percent_change_from_baseline','residential_percent_change_from_baseline' ]]
#Mudando nome da coluna pra ficar igual a tabela de oxford
df_mobility_mod.rename(columns={'date': 'Date'}, inplace = True)
df_mobility_mod.head()

<ipython-input-32-ca5205e34382>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_mobility_mod.rename(columns={'date': 'Date'}, inplace = True)

,Date,country_region,sub_region_1,metro_area,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,2020-02-15,United Arab Emirates,NaN,NaN,0.0,4.0,5.0,0.0,2.0,1.0
1,2020-02-16,United Arab Emirates,NaN,NaN,1.0,4.0,4.0,1.0,2.0,1.0
2,2020-02-17,United Arab Emirates,NaN,NaN,-1.0,1.0,5.0,1.0,2.0,1.0
3,2020-02-18,United Arab Emirates,NaN,NaN,-2.0,1.0,5.0,0.0,2.0,1.0
4,2020-02-19,United Arab Emirates,NaN,NaN,-2.0,0.0,4.0,-1.0,2.0,1.0

##3 - Filtrando dados

Seleção de países

In [ ]:
lista_completa_de_paises = [
      'Argentina',
			'Bolivia'  ,
			'Brazil'  ,
			'Chile',
			'Colombia',
			'Costa Rica',
			'Cuba',
			'Ecuador',
			'El Salvador',
			'Guatemala',
			'Haiti',
			'Honduras',
			'Mexico',
			'Nicaragua',
			'Panama',
			'Paraguay',
			'Peru',
			'Dominican Republic',
			'Uruguay',
			'Venezuela']
df_LAT = df_LAT[df_LAT['CountryName'].isin(lista_completa_de_paises)].reset_index(drop = True)
df_Vacinacao_mod = df_Vacinacao_mod[df_Vacinacao_mod['location'].isin(lista_completa_de_paises)].reset_index(drop = True)
df_socio_economic = df_socio_economic[df_socio_economic['Country Name'].isin(lista_completa_de_paises)].reset_index(drop = True)

In [ ]:
df_Vacinacao_mod.head()

,Date,location,new_cases,total_tests,new_deaths,new_tests,median_age,aged_65_older,aged_70_older,population,...,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,new_vaccinations_smoothed,total_vaccinations_per_hundred,people_vaccinated_per_hundred,total_boosters_per_hundred,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed_per_hundred
0,2020-01-01,Argentina,NaN,4.0,NaN,4.0,31.9,11.198,7.441,45510324.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-01-02,Argentina,NaN,99.0,NaN,95.0,31.9,11.198,7.441,45510324.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-01-03,Argentina,0.0,104.0,0.0,5.0,31.9,11.198,7.441,45510324.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-01-04,Argentina,0.0,180.0,0.0,76.0,31.9,11.198,7.441,45510324.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-01-05,Argentina,0.0,194.0,0.0,14.0,31.9,11.198,7.441,45510324.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

##4 - Tratando dados

Transformando a data em formato datetime

In [ ]:
from datetime import datetime as dt


df_LAT.Date = df_LAT.Date.map(str) # primeiro transformando os dados em string
df_LAT.Date = pd.to_datetime(df_LAT.Date)  # depois transformando em date

df_mobility_mod.Date = df_mobility_mod.Date.map(str)
df_mobility_mod.Date = pd.to_datetime(df_mobility_mod.Date)

df_Vacinacao_mod.Date = df_Vacinacao_mod.Date.map(str)
df_Vacinacao_mod.Date = pd.to_datetime(df_Vacinacao_mod.Date)


df_Vacinacao_mod.info

<ipython-input-35-7683af60b60c>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_mobility_mod.Date = df_mobility_mod.Date.map(str)
<ipython-input-35-7683af60b60c>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_mobility_mod.Date = pd.to_datetime(df_mobility_mod.Date)

<bound method DataFrame.info of             Date   location  new_cases  total_tests  new_deaths  new_tests  \
0     2020-01-01  Argentina        NaN          4.0         NaN        4.0
1     2020-01-02  Argentina        NaN         99.0         NaN       95.0
2     2020-01-03  Argentina        0.0        104.0         0.0        5.0
3     2020-01-04  Argentina        0.0        180.0         0.0       76.0
4     2020-01-05  Argentina        0.0        194.0         0.0       14.0
...          ...        ...        ...          ...         ...        ...
26439 2023-08-12  Venezuela        0.0          NaN         0.0        NaN
26440 2023-08-13  Venezuela        0.0          NaN         0.0        NaN
26441 2023-08-14  Venezuela        0.0          NaN         0.0        NaN
26442 2023-08-15  Venezuela        0.0          NaN         0.0        NaN
26443 2023-08-16  Venezuela        0.0          NaN         0.0        NaN

       median_age  aged_65_older  aged_70_older  population  ...  \
0            31.9         11.198          7.441  45510324.0  ...
1            31.9         11.198          7.441  45510324.0  ...
2            31.9         11.198          7.441  45510324.0  ...
3            31.9         11.198          7.441  45510324.0  ...
4            31.9         11.198          7.441  45510324.0  ...
...           ...            ...            ...         ...  ...
26439        29.0          6.614          3.915  28301700.0  ...
26440        29.0          6.614          3.915  28301700.0  ...
26441        29.0          6.614          3.915  28301700.0  ...
26442        29.0          6.614          3.915  28301700.0  ...
26443        29.0          6.614          3.915  28301700.0  ...

       people_vaccinated  people_fully_vaccinated  total_boosters  \
0                    NaN                      NaN             NaN
1                    NaN                      NaN             NaN
2                    NaN                      NaN             NaN
3                    NaN                      NaN             NaN
4                    NaN                      NaN             NaN
...                  ...                      ...             ...
26439                NaN                      NaN             NaN
26440                NaN                      NaN             NaN
26441                NaN                      NaN             NaN
26442                NaN                      NaN             NaN
26443                NaN                      NaN             NaN

       new_vaccinations  new_vaccinations_smoothed  \
0                   NaN                        NaN
1                   NaN                        NaN
2                   NaN                        NaN
3                   NaN                        NaN
4                   NaN                        NaN
...                 ...                        ...
26439               NaN                        NaN
26440               NaN                        NaN
26441               NaN                        NaN
26442               NaN                        NaN
26443               NaN                        NaN

       total_vaccinations_per_hundred  people_vaccinated_per_hundred  \
0                                 NaN                            NaN
1                                 NaN                            NaN
2                                 NaN                            NaN
3                                 NaN                            NaN
4                                 NaN                            NaN
...                               ...                            ...
26439                             NaN                            NaN
26440                             NaN                            NaN
26441                             NaN                            NaN
26442                             NaN                            NaN
26443                             NaN                            NaN

       total_boosters_per_hundred  new_vaccinations_smoothed_per_million  \
0                             NaN                                    NaN
1                             NaN                                    NaN
2                             NaN                                    NaN
3                             NaN                                    NaN
4                             NaN                                    NaN
...                           ...                                    ...
26439                         NaN                                    NaN
26440                         NaN                                    NaN
26441                         NaN                                    NaN
26442                         NaN                                    NaN
26443                         NaN                                    NaN

       new_people_vaccinated_smoothed_per_hundred
0                                             NaN
1                                             NaN
2                                             NaN
3                                             NaN
4                                             NaN
...                                           ...
26439                                         NaN
26440                                         NaN
26441                                         NaN
26442                                         NaN
26443                                         NaN

[26444 rows x 26 columns]>

Criado a coluna que indica o dia do ano

In [ ]:
df_LAT['Day']= df_LAT.Date.dt.day_of_year #Aproveitando para criar a coluna dia do ano
df_LAT['Year']= df_LAT.Date.dt.year   #Aproveitando para criar a coluna dia do ano

In [ ]:
df_LAT.columns

Index(['CountryName', 'CountryCode', 'RegionName', 'RegionCode',
       'Jurisdiction', 'Date', 'C1_School closing', 'C1_Flag',
       'C2_Workplace closing', 'C2_Flag', 'C3_Cancel public events', 'C3_Flag',
       'C4_Restrictions on gatherings', 'C4_Flag', 'C5_Close public transport',
       'C5_Flag', 'C6_Stay at home requirements', 'C6_Flag',
       'C7_Restrictions on internal movement', 'C7_Flag',
       'C8_International travel controls', 'E1_Income support', 'E1_Flag',
       'E2_Debt/contract relief', 'E3_Fiscal measures',
       'E4_International support', 'H1_Public information campaigns',
       'H1_Flag', 'H2_Testing policy', 'H3_Contact tracing',
       'H4_Emergency investment in healthcare', 'H5_Investment in vaccines',
       'H6_Facial Coverings', 'H6_Flag', 'H7_Vaccination policy', 'H7_Flag',
       'H8_Protection of elderly people', 'H8_Flag', 'M1_Wildcard',
       'V1_Vaccine Prioritisation (summary)',
       'V2A_Vaccine Availability (summary)',
       'V2B_Vaccine age eligibility/availability age floor (general population summary)',
       'V2C_Vaccine age eligibility/availability age floor (at risk summary)',
       'V2D_Medically/ clinically vulnerable (Non-elderly)', 'V2E_Education',
       'V2F_Frontline workers  (non healthcare)',
       'V2G_Frontline workers  (healthcare)',
       'V3_Vaccine Financial Support (summary)',
       'V4_Mandatory Vaccination (summary)', 'ConfirmedCases',
       'ConfirmedDeaths', 'StringencyIndex', 'StringencyIndexForDisplay',
       'StringencyLegacyIndex', 'StringencyLegacyIndexForDisplay',
       'GovernmentResponseIndex', 'GovernmentResponseIndexForDisplay',
       'ContainmentHealthIndex', 'ContainmentHealthIndexForDisplay',
       'EconomicSupportIndex', 'EconomicSupportIndexForDisplay', 'Day',
       'Year'],
      dtype='object')

Agora Fazendo a Média Móvel do número de casos confirmados e número de mortos para cada pais

Primeiro separa-se os paises em dataframes para fazer a média móvel semanal em cada um desses dataframes

In [ ]:
df_Vacinacao_mod_Brazil             = df_Vacinacao_mod[df_Vacinacao_mod.location == 'Brazil'].set_index('Date').sort_index().fillna(0)
df_Vacinacao_mod_Argentina         = df_Vacinacao_mod[df_Vacinacao_mod.location == 'Argentina'     ].set_index('Date').sort_index().fillna(0)
df_Vacinacao_mod_Bolivia			     = df_Vacinacao_mod[df_Vacinacao_mod.location == 'Bolivia'       ].set_index('Date').sort_index().fillna(0)
df_Vacinacao_mod_Chile             = df_Vacinacao_mod[df_Vacinacao_mod.location == 'Chile'         ].set_index('Date').sort_index().fillna(0)
df_Vacinacao_mod_Colombia          = df_Vacinacao_mod[df_Vacinacao_mod.location == 'Colombia'      ].set_index('Date').sort_index().fillna(0)
df_Vacinacao_mod_CostaRica         = df_Vacinacao_mod[df_Vacinacao_mod.location == 'Costa Rica'    ].set_index('Date').sort_index().fillna(0)
df_Vacinacao_mod_Cuba					     = df_Vacinacao_mod[df_Vacinacao_mod.location == 'Cuba'          ].set_index('Date').sort_index().fillna(0)
df_Vacinacao_mod_Ecuador				   = df_Vacinacao_mod[df_Vacinacao_mod.location == 'Ecuador'       ].set_index('Date').sort_index().fillna(0)
df_Vacinacao_mod_ElSalvador        = df_Vacinacao_mod[df_Vacinacao_mod.location == 'El Salvador'   ].set_index('Date').sort_index().fillna(0)
df_Vacinacao_mod_Guatemala	  		 = df_Vacinacao_mod[df_Vacinacao_mod.location == 'Guatemala'     ].set_index('Date').sort_index().fillna(0)
df_Vacinacao_mod_Haiti				     = df_Vacinacao_mod[df_Vacinacao_mod.location == 'Haiti'			].set_index('Date').sort_index().fillna(0)
df_Vacinacao_mod_Honduras				   = df_Vacinacao_mod[df_Vacinacao_mod.location == 'Honduras'      ].set_index('Date').sort_index().fillna(0)
df_Vacinacao_mod_Mexico				     = df_Vacinacao_mod[df_Vacinacao_mod.location == 'Mexico'        ].set_index('Date').sort_index().fillna(0)
df_Vacinacao_mod_Nicaragua			   = df_Vacinacao_mod[df_Vacinacao_mod.location == 'Nicaragua'     ].set_index('Date').sort_index().fillna(0)
df_Vacinacao_mod_Panama				     = df_Vacinacao_mod[df_Vacinacao_mod.location == 'Panama'        ].set_index('Date').sort_index().fillna(0)
df_Vacinacao_mod_Paraguay				   = df_Vacinacao_mod[df_Vacinacao_mod.location == 'Paraguay'      ].set_index('Date').sort_index().fillna(0)
df_Vacinacao_mod_Peru					     = df_Vacinacao_mod[df_Vacinacao_mod.location == 'Peru'          ].set_index('Date').sort_index().fillna(0)
df_Vacinacao_mod_DominicanRepublic = df_Vacinacao_mod[df_Vacinacao_mod.location == 'Dominican Republic'    ].set_index('Date').sort_index().fillna(0)
df_Vacinacao_mod_Uruguay           = df_Vacinacao_mod[df_Vacinacao_mod.location == 'Uruguay'       ].set_index('Date').sort_index().fillna(0)
df_Vacinacao_mod_Venezuela		     = df_Vacinacao_mod[df_Vacinacao_mod.location == 'Venezuela'     ].set_index('Date').sort_index().fillna(0)

Fazendo o cálculo da média móvel

In [ ]:
df_Vacinacao_mod_Argentina['new_deaths_mm7']             = df_Vacinacao_mod_Argentina['new_deaths'].rolling(window = 7).mean()
df_Vacinacao_mod_Bolivia['new_deaths_mm7']			    = df_Vacinacao_mod_Bolivia['new_deaths'].rolling(window = 7).mean()
df_Vacinacao_mod_Brazil['new_deaths_mm7']                = df_Vacinacao_mod_Brazil['new_deaths'].rolling(window = 7).mean()
df_Vacinacao_mod_Chile['new_deaths_mm7']                 = df_Vacinacao_mod_Chile['new_deaths'].rolling(window = 7).mean()
df_Vacinacao_mod_Colombia['new_deaths_mm7']              = df_Vacinacao_mod_Colombia['new_deaths'].rolling(window = 7).mean()
df_Vacinacao_mod_CostaRica['new_deaths_mm7']            = df_Vacinacao_mod_CostaRica['new_deaths'].rolling(window = 7).mean()
df_Vacinacao_mod_Cuba['new_deaths_mm7']					= df_Vacinacao_mod_Cuba['new_deaths'].rolling(window = 7).mean()
df_Vacinacao_mod_Ecuador['new_deaths_mm7']				= df_Vacinacao_mod_Ecuador['new_deaths' ].rolling(window = 7).mean()
df_Vacinacao_mod_ElSalvador['new_deaths_mm7']           = df_Vacinacao_mod_ElSalvador['new_deaths'].rolling(window = 7).mean()
df_Vacinacao_mod_Guatemala['new_deaths_mm7']			    = df_Vacinacao_mod_Guatemala['new_deaths'].rolling(window = 7).mean()
df_Vacinacao_mod_Haiti['new_deaths_mm7']				    = df_Vacinacao_mod_Haiti['new_deaths'].rolling(window = 7).mean()
df_Vacinacao_mod_Honduras['new_deaths_mm7']				= df_Vacinacao_mod_Honduras['new_deaths'].rolling(window = 7).mean()
df_Vacinacao_mod_Mexico['new_deaths_mm7']				= df_Vacinacao_mod_Mexico['new_deaths'].rolling(window = 7).mean()
df_Vacinacao_mod_Nicaragua['new_deaths_mm7']			    = df_Vacinacao_mod_Nicaragua['new_deaths'].rolling(window = 7).mean()
df_Vacinacao_mod_Panama['new_deaths_mm7']				= df_Vacinacao_mod_Panama['new_deaths'].rolling(window = 7).mean()
df_Vacinacao_mod_Paraguay['new_deaths_mm7']			    = df_Vacinacao_mod_Paraguay['new_deaths'].rolling(window = 7).mean()
df_Vacinacao_mod_Peru['new_deaths_mm7']				    = df_Vacinacao_mod_Peru['new_deaths' ].rolling(window = 7).mean()
df_Vacinacao_mod_DominicanRepublic['new_deaths_mm7']    = df_Vacinacao_mod_DominicanRepublic['new_deaths'].rolling(window = 7).mean()
df_Vacinacao_mod_Uruguay['new_deaths_mm7']               = df_Vacinacao_mod_Uruguay['new_deaths'].rolling(window = 7).mean()
df_Vacinacao_mod_Venezuela['new_deaths_mm7']		        = df_Vacinacao_mod_Venezuela['new_deaths'].rolling(window = 7).mean()

In [ ]:
df_Vacinacao_mod_Argentina['new_cases_mm7']             = df_Vacinacao_mod_Argentina['new_cases'].rolling(window = 7).mean()
df_Vacinacao_mod_Bolivia['new_cases_mm7']			    = df_Vacinacao_mod_Bolivia['new_cases'].rolling(window = 7).mean()
df_Vacinacao_mod_Brazil['new_cases_mm7']                = df_Vacinacao_mod_Brazil['new_cases'].rolling(window = 7).mean()
df_Vacinacao_mod_Chile['new_cases_mm7']                 = df_Vacinacao_mod_Chile['new_cases'].rolling(window = 7).mean()
df_Vacinacao_mod_Colombia['new_cases_mm7']              = df_Vacinacao_mod_Colombia['new_cases'].rolling(window = 7).mean()
df_Vacinacao_mod_CostaRica['new_cases_mm7']            = df_Vacinacao_mod_CostaRica['new_cases'].rolling(window = 7).mean()
df_Vacinacao_mod_Cuba['new_cases_mm7']					= df_Vacinacao_mod_Cuba['new_cases'].rolling(window = 7).mean()
df_Vacinacao_mod_Ecuador['new_cases_mm7']				= df_Vacinacao_mod_Ecuador['new_cases' ].rolling(window = 7).mean()
df_Vacinacao_mod_ElSalvador['new_cases_mm7']           = df_Vacinacao_mod_ElSalvador['new_cases'].rolling(window = 7).mean()
df_Vacinacao_mod_Guatemala['new_cases_mm7']			    = df_Vacinacao_mod_Guatemala['new_cases'].rolling(window = 7).mean()
df_Vacinacao_mod_Haiti['new_cases_mm7']				    = df_Vacinacao_mod_Haiti['new_cases'].rolling(window = 7).mean()
df_Vacinacao_mod_Honduras['new_cases_mm7']				= df_Vacinacao_mod_Honduras['new_cases'].rolling(window = 7).mean()
df_Vacinacao_mod_Mexico['new_cases_mm7']				= df_Vacinacao_mod_Mexico['new_cases'].rolling(window = 7).mean()
df_Vacinacao_mod_Nicaragua['new_cases_mm7']			    = df_Vacinacao_mod_Nicaragua['new_cases'].rolling(window = 7).mean()
df_Vacinacao_mod_Panama['new_cases_mm7']				= df_Vacinacao_mod_Panama['new_cases'].rolling(window = 7).mean()
df_Vacinacao_mod_Paraguay['new_cases_mm7']			    = df_Vacinacao_mod_Paraguay['new_cases'].rolling(window = 7).mean()
df_Vacinacao_mod_Peru['new_cases_mm7']				    = df_Vacinacao_mod_Peru['new_cases' ].rolling(window = 7).mean()
df_Vacinacao_mod_DominicanRepublic['new_cases_mm7']    = df_Vacinacao_mod_DominicanRepublic['new_cases'].rolling(window = 7).mean()
df_Vacinacao_mod_Uruguay['new_cases_mm7']               = df_Vacinacao_mod_Uruguay['new_cases'].rolling(window = 7).mean()
df_Vacinacao_mod_Venezuela['new_cases_mm7']		        = df_Vacinacao_mod_Venezuela['new_cases'].rolling(window = 7).mean()

Tratando as tabelas de mobilidade para cada país

In [ ]:
df_Mob_Argentina = df_mobility_mod[df_mobility.country_region == 'Argentina' ]
df_Mob_Brazil = df_mobility_mod[df_mobility.country_region == 'Brazil' ]
df_Mob_Bolivia = df_mobility_mod[df_mobility.country_region == 'Bolivia' ]
df_Mob_Chile = df_mobility_mod[df_mobility.country_region == 'Chile' ]
df_Mob_Colombia = df_mobility_mod[df_mobility.country_region == 'Colombia' ]
df_Mob_CostaRica = df_mobility_mod[df_mobility.country_region == 'Costa Rica' ]
df_Mob_Cuba = df_mobility_mod[df_mobility.country_region == 'Cuba' ]
df_Mob_Ecuador = df_mobility_mod[df_mobility.country_region == 'Ecuador' ]
df_Mob_ElSalvador = df_mobility_mod[df_mobility.country_region == 'El Salvador' ]
df_Mob_Guatemala = df_mobility_mod[df_mobility.country_region == 'Guatemala' ]
df_Mob_Haiti = df_mobility_mod[df_mobility.country_region == 'Haiti' ]
df_Mob_Honduras = df_mobility_mod[df_mobility.country_region == 'Honduras' ]
df_Mob_Mexico = df_mobility_mod[df_mobility.country_region == 'Mexico' ]
df_Mob_Nicaragua = df_mobility_mod[df_mobility.country_region == 'Nicaragua' ]
df_Mob_Panama = df_mobility_mod[df_mobility.country_region == 'Panama' ]
df_Mob_Paraguay = df_mobility_mod[df_mobility.country_region == 'Paraguay' ]
df_Mob_Peru = df_mobility_mod[df_mobility.country_region == 'Peru' ]
df_Mob_DominicanRepublic = df_mobility_mod[df_mobility.country_region == 'Dominican Republic' ]
df_Mob_Uruguay = df_mobility_mod[df_mobility.country_region == 'Uruguay' ]
df_Mob_Venezuela = df_mobility_mod[df_mobility.country_region == 'Venezuela' ]

df_Mob_Venezuela.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 974 entries, 11636737 to 11637710
Data columns (total 10 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   Date                                                974 non-null    datetime64[ns]
 1   country_region                                      974 non-null    object
 2   sub_region_1                                        0 non-null      object
 3   metro_area                                          0 non-null      object
 4   retail_and_recreation_percent_change_from_baseline  974 non-null    float64
 5   grocery_and_pharmacy_percent_change_from_baseline   974 non-null    float64
 6   parks_percent_change_from_baseline                  974 non-null    float64
 7   transit_stations_percent_change_from_baseline       974 non-null    float64
 8   workplaces_percent_change_from_baseline             974 non-null    float64
 9   residential_percent_change_from_baseline            974 non-null    float64
dtypes: datetime64[ns](1), float64(6), object(3)
memory usage: 83.7+ KB

Colocando apenas as informações referentes ao país e tirando as informações que se referem a regiões daquele país

In [ ]:
df_Mob_Argentina = df_Mob_Argentina[df_Mob_Argentina['sub_region_1'].isna() ]
df_Mob_Bolivia = df_Mob_Bolivia[df_Mob_Bolivia['sub_region_1'].isna() ]
df_Mob_Brazil = df_Mob_Brazil[df_Mob_Brazil['sub_region_1'].isna() ]
df_Mob_Chile = df_Mob_Chile[df_Mob_Chile['sub_region_1'].isna() ]
df_Mob_Colombia = df_Mob_Colombia[df_Mob_Colombia['sub_region_1'].isna()]
df_Mob_CostaRica = df_Mob_CostaRica[df_Mob_CostaRica['sub_region_1'].isna() ]
df_Mob_Cuba = df_Mob_Cuba[df_Mob_Cuba['sub_region_1'].isna()]
df_Mob_Ecuador = df_Mob_Ecuador[df_Mob_Ecuador['sub_region_1'].isna() ]
df_Mob_ElSalvador = df_Mob_ElSalvador[df_Mob_ElSalvador['sub_region_1'].isna() ]
df_Mob_Guatemala = df_Mob_Guatemala[df_Mob_Guatemala['sub_region_1'].isna() ]
df_Mob_Haiti = df_Mob_Haiti[df_Mob_Haiti['sub_region_1'].isna() ]
df_Mob_Honduras = df_Mob_Honduras[df_Mob_Honduras['sub_region_1'].isna() ]
df_Mob_Mexico = df_Mob_Mexico[df_Mob_Mexico['sub_region_1'].isna()]
df_Mob_Nicaragua = df_Mob_Nicaragua[df_Mob_Nicaragua['sub_region_1'].isna() ]
df_Mob_Panama = df_Mob_Panama[df_Mob_Panama['sub_region_1'].isna() ]
df_Mob_Paraguay = df_Mob_Paraguay[df_Mob_Paraguay['sub_region_1'].isna() ]
df_Mob_Peru = df_Mob_Peru[df_Mob_Peru['sub_region_1'].isna() ]
df_Mob_DominicanRepublic = df_Mob_DominicanRepublic[df_Mob_DominicanRepublic['sub_region_1'].isna() ]
df_Mob_Uruguay = df_Mob_Uruguay[df_Mob_Uruguay['sub_region_1'].isna() ]
df_Mob_Venezuela = df_Mob_Venezuela[df_Mob_Venezuela['sub_region_1'].isna()]

In [ ]:
df_Mob_Haiti = df_Mob_Haiti[df_Mob_Haiti['metro_area'].isna() ]
df_Mob_Nicaragua = df_Mob_Nicaragua[df_Mob_Nicaragua['metro_area'].isna() ]
df_Mob_Panama = df_Mob_Panama[df_Mob_Panama['metro_area'].isna() ]
df_Mob_Uruguay = df_Mob_Uruguay[df_Mob_Uruguay['metro_area'].isna() ]

In [ ]:
df_Vacinacao_mod_Argentina = pd.merge(df_Vacinacao_mod_Argentina,df_Mob_Argentina, on='Date',how='left')
df_Vacinacao_mod_Argentina.head()

,Date,location,new_cases,total_tests,new_deaths,new_tests,median_age,aged_65_older,aged_70_older,population,...,new_cases_mm7,country_region,sub_region_1,metro_area,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,2020-01-01,Argentina,0.0,4.0,0.0,4.0,31.9,11.198,7.441,45510324.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-01-02,Argentina,0.0,99.0,0.0,95.0,31.9,11.198,7.441,45510324.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-01-03,Argentina,0.0,104.0,0.0,5.0,31.9,11.198,7.441,45510324.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-01-04,Argentina,0.0,180.0,0.0,76.0,31.9,11.198,7.441,45510324.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-01-05,Argentina,0.0,194.0,0.0,14.0,31.9,11.198,7.441,45510324.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Juntando dados de mobilidade com os dados de contenção para cada país

In [ ]:
df_Vacinacao_mod_Brazil = pd.merge(df_Vacinacao_mod_Brazil,df_Mob_Brazil, on='Date',how='left')
df_Vacinacao_mod_Bolivia = pd.merge(df_Vacinacao_mod_Bolivia,df_Mob_Bolivia, on='Date',how='left')
df_Vacinacao_mod_Chile = pd.merge(df_Vacinacao_mod_Chile,df_Mob_Chile, on='Date',how='left')
df_Vacinacao_mod_Colombia = pd.merge(df_Vacinacao_mod_Colombia,df_Mob_Colombia, on='Date',how='left')
df_Vacinacao_mod_CostaRica = pd.merge(df_Vacinacao_mod_CostaRica,df_Mob_CostaRica, on='Date',how='left')
df_Vacinacao_mod_Cuba = pd.merge(df_Vacinacao_mod_Cuba,df_Mob_Cuba, on='Date',how='left')
df_Vacinacao_mod_Ecuador = pd.merge(df_Vacinacao_mod_Ecuador,df_Mob_Ecuador, on='Date',how='left')
df_Vacinacao_mod_ElSalvador = pd.merge(df_Vacinacao_mod_ElSalvador,df_Mob_ElSalvador, on='Date',how='left')
df_Vacinacao_mod_Guatemala = pd.merge(df_Vacinacao_mod_Guatemala,df_Mob_Guatemala, on='Date',how='left')
df_Vacinacao_mod_Haiti = pd.merge(df_Vacinacao_mod_Haiti,df_Mob_Haiti, on='Date',how='left')
df_Vacinacao_mod_Honduras = pd.merge(df_Vacinacao_mod_Honduras,df_Mob_Honduras, on='Date',how='left')
df_Vacinacao_mod_Mexico = pd.merge(df_Vacinacao_mod_Mexico,df_Mob_Mexico, on='Date',how='left')
df_Vacinacao_mod_Nicaragua = pd.merge(df_Vacinacao_mod_Nicaragua,df_Mob_Nicaragua, on='Date',how='left')
df_Vacinacao_mod_Panama = pd.merge(df_Vacinacao_mod_Panama,df_Mob_Panama, on='Date',how='left')
df_Vacinacao_mod_Paraguay = pd.merge(df_Vacinacao_mod_Paraguay,df_Mob_Paraguay, on='Date',how='left')
df_Vacinacao_mod_Peru = pd.merge(df_Vacinacao_mod_Peru,df_Mob_Peru, on='Date',how='left')
df_Vacinacao_mod_DominicanRepublic = pd.merge(df_Vacinacao_mod_DominicanRepublic,df_Mob_DominicanRepublic, on='Date',how='left')
df_Vacinacao_mod_Uruguay = pd.merge(df_Vacinacao_mod_Uruguay,df_Mob_Uruguay, on='Date',how='left')
df_Vacinacao_mod_Venezuela = pd.merge(df_Vacinacao_mod_Venezuela,df_Mob_Venezuela, on='Date',how='left')

In [ ]:
df_Vacinacao_mod.columns

Index(['Date', 'location', 'new_cases', 'total_tests', 'new_deaths',
       'new_tests', 'median_age', 'aged_65_older', 'aged_70_older',
       'population', 'human_development_index', 'life_expectancy',
       'gdp_per_capita', 'extreme_poverty', 'hospital_beds_per_thousand',
       'total_vaccinations', 'people_vaccinated', 'people_fully_vaccinated',
       'total_boosters', 'new_vaccinations', 'new_vaccinations_smoothed',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'total_boosters_per_hundred', 'new_vaccinations_smoothed_per_million',
       'new_people_vaccinated_smoothed_per_hundred'],
      dtype='object')

Juntando as bases novamente

In [ ]:
df_LAT_fim0 = pd.concat([df_Vacinacao_mod_Argentina,df_Vacinacao_mod_Bolivia,df_Vacinacao_mod_Brazil,df_Vacinacao_mod_Chile,df_Vacinacao_mod_Colombia,df_Vacinacao_mod_CostaRica,df_Vacinacao_mod_Cuba,df_Vacinacao_mod_Ecuador,df_Vacinacao_mod_ElSalvador,df_Vacinacao_mod_Guatemala])

In [ ]:
df_LAT_fim0.columns

Index(['Date', 'location', 'new_cases', 'total_tests', 'new_deaths',
       'new_tests', 'median_age', 'aged_65_older', 'aged_70_older',
       'population', 'human_development_index', 'life_expectancy',
       'gdp_per_capita', 'extreme_poverty', 'hospital_beds_per_thousand',
       'total_vaccinations', 'people_vaccinated', 'people_fully_vaccinated',
       'total_boosters', 'new_vaccinations', 'new_vaccinations_smoothed',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'total_boosters_per_hundred', 'new_vaccinations_smoothed_per_million',
       'new_people_vaccinated_smoothed_per_hundred', 'new_deaths_mm7',
       'new_cases_mm7', 'country_region', 'sub_region_1', 'metro_area',
       'retail_and_recreation_percent_change_from_baseline',
       'grocery_and_pharmacy_percent_change_from_baseline',
       'parks_percent_change_from_baseline',
       'transit_stations_percent_change_from_baseline',
       'workplaces_percent_change_from_baseline',
       'residential_percent_change_from_baseline'],
      dtype='object')

In [ ]:
df_LAT_fim = pd.concat([df_LAT_fim0, df_Vacinacao_mod_Haiti,df_Vacinacao_mod_Honduras,df_Vacinacao_mod_Mexico,df_Vacinacao_mod_Nicaragua,df_Vacinacao_mod_Panama,df_Vacinacao_mod_Paraguay,df_Vacinacao_mod_Peru,df_Vacinacao_mod_DominicanRepublic,df_Vacinacao_mod_Uruguay,df_Vacinacao_mod_Venezuela])

In [ ]:
df_LAT.columns

Index(['CountryName', 'CountryCode', 'RegionName', 'RegionCode',
       'Jurisdiction', 'Date', 'C1_School closing', 'C1_Flag',
       'C2_Workplace closing', 'C2_Flag', 'C3_Cancel public events', 'C3_Flag',
       'C4_Restrictions on gatherings', 'C4_Flag', 'C5_Close public transport',
       'C5_Flag', 'C6_Stay at home requirements', 'C6_Flag',
       'C7_Restrictions on internal movement', 'C7_Flag',
       'C8_International travel controls', 'E1_Income support', 'E1_Flag',
       'E2_Debt/contract relief', 'E3_Fiscal measures',
       'E4_International support', 'H1_Public information campaigns',
       'H1_Flag', 'H2_Testing policy', 'H3_Contact tracing',
       'H4_Emergency investment in healthcare', 'H5_Investment in vaccines',
       'H6_Facial Coverings', 'H6_Flag', 'H7_Vaccination policy', 'H7_Flag',
       'H8_Protection of elderly people', 'H8_Flag', 'M1_Wildcard',
       'V1_Vaccine Prioritisation (summary)',
       'V2A_Vaccine Availability (summary)',
       'V2B_Vaccine age eligibility/availability age floor (general population summary)',
       'V2C_Vaccine age eligibility/availability age floor (at risk summary)',
       'V2D_Medically/ clinically vulnerable (Non-elderly)', 'V2E_Education',
       'V2F_Frontline workers  (non healthcare)',
       'V2G_Frontline workers  (healthcare)',
       'V3_Vaccine Financial Support (summary)',
       'V4_Mandatory Vaccination (summary)', 'ConfirmedCases',
       'ConfirmedDeaths', 'StringencyIndex', 'StringencyIndexForDisplay',
       'StringencyLegacyIndex', 'StringencyLegacyIndexForDisplay',
       'GovernmentResponseIndex', 'GovernmentResponseIndexForDisplay',
       'ContainmentHealthIndex', 'ContainmentHealthIndexForDisplay',
       'EconomicSupportIndex', 'EconomicSupportIndexForDisplay', 'Day',
       'Year'],
      dtype='object')

In [ ]:
df_LAT_final = pd.merge(df_LAT_fim, df_LAT, left_on=['Date', 'location'], right_on=['Date', 'CountryName'], how='right')

In [ ]:
df_LAT_final.columns

Index(['Date', 'location', 'new_cases', 'total_tests', 'new_deaths',
       'new_tests', 'median_age', 'aged_65_older', 'aged_70_older',
       'population', 'human_development_index', 'life_expectancy',
       'gdp_per_capita', 'extreme_poverty', 'hospital_beds_per_thousand',
       'total_vaccinations', 'people_vaccinated', 'people_fully_vaccinated',
       'total_boosters', 'new_vaccinations', 'new_vaccinations_smoothed',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'total_boosters_per_hundred', 'new_vaccinations_smoothed_per_million',
       'new_people_vaccinated_smoothed_per_hundred', 'new_deaths_mm7',
       'new_cases_mm7', 'country_region', 'sub_region_1', 'metro_area',
       'retail_and_recreation_percent_change_from_baseline',
       'grocery_and_pharmacy_percent_change_from_baseline',
       'parks_percent_change_from_baseline',
       'transit_stations_percent_change_from_baseline',
       'workplaces_percent_change_from_baseline',
       'residential_percent_change_from_baseline', 'CountryName',
       'CountryCode', 'RegionName', 'RegionCode', 'Jurisdiction',
       'C1_School closing', 'C1_Flag', 'C2_Workplace closing', 'C2_Flag',
       'C3_Cancel public events', 'C3_Flag', 'C4_Restrictions on gatherings',
       'C4_Flag', 'C5_Close public transport', 'C5_Flag',
       'C6_Stay at home requirements', 'C6_Flag',
       'C7_Restrictions on internal movement', 'C7_Flag',
       'C8_International travel controls', 'E1_Income support', 'E1_Flag',
       'E2_Debt/contract relief', 'E3_Fiscal measures',
       'E4_International support', 'H1_Public information campaigns',
       'H1_Flag', 'H2_Testing policy', 'H3_Contact tracing',
       'H4_Emergency investment in healthcare', 'H5_Investment in vaccines',
       'H6_Facial Coverings', 'H6_Flag', 'H7_Vaccination policy', 'H7_Flag',
       'H8_Protection of elderly people', 'H8_Flag', 'M1_Wildcard',
       'V1_Vaccine Prioritisation (summary)',
       'V2A_Vaccine Availability (summary)',
       'V2B_Vaccine age eligibility/availability age floor (general population summary)',
       'V2C_Vaccine age eligibility/availability age floor (at risk summary)',
       'V2D_Medically/ clinically vulnerable (Non-elderly)', 'V2E_Education',
       'V2F_Frontline workers  (non healthcare)',
       'V2G_Frontline workers  (healthcare)',
       'V3_Vaccine Financial Support (summary)',
       'V4_Mandatory Vaccination (summary)', 'ConfirmedCases',
       'ConfirmedDeaths', 'StringencyIndex', 'StringencyIndexForDisplay',
       'StringencyLegacyIndex', 'StringencyLegacyIndexForDisplay',
       'GovernmentResponseIndex', 'GovernmentResponseIndexForDisplay',
       'ContainmentHealthIndex', 'ContainmentHealthIndexForDisplay',
       'EconomicSupportIndex', 'EconomicSupportIndexForDisplay', 'Day',
       'Year'],
      dtype='object')

Dataset final

In [ ]:
df_socio_economic['Year'].astype(int)
#df_socio_economic['Year'] = df_socio_economic.to_numeric(df_socio_economic['Year'], errors = 'coerce')
df_socio_economic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   hdi           40 non-null     float64
 1   le            40 non-null     float64
 2   eys           40 non-null     float64
 3   mys           40 non-null     float64
 4   gnipc         40 non-null     float64
 5   Country Code  40 non-null     object
 6   PIB           37 non-null     float64
 7   Country Name  40 non-null     object
 8   Gini          24 non-null     float64
 9   Year          40 non-null     int64
dtypes: float64(7), int64(1), object(2)
memory usage: 3.2+ KB

In [ ]:
df_LAT_final.Year

0        2020
1        2020
2        2020
3        2020
4        2020
         ...
21915    2022
21916    2022
21917    2022
21918    2022
21919    2022
Name: Year, Length: 21920, dtype: int64

In [ ]:
df_LAT_final = pd.merge(df_LAT_final,df_socio_economic, left_on=['Year', 'CountryCode'], right_on=['Year','Country Code'],how='left')

In [ ]:
df_LAT_final.reset_index()

,index,Date,location,new_cases,total_tests,new_deaths,new_tests,median_age,aged_65_older,aged_70_older,...,Year,hdi,le,eys,mys,gnipc,Country Code,PIB,Country Name,Gini
0,0,2020-01-01,Argentina,0.0,4.0,0.0,4.0,31.9,11.198,7.441,...,2020,0.84,75.8921,17.87487,11.147269,19178.33184,ARG,8496.428157,Argentina,42.3
1,1,2020-01-02,Argentina,0.0,99.0,0.0,95.0,31.9,11.198,7.441,...,2020,0.84,75.8921,17.87487,11.147269,19178.33184,ARG,8496.428157,Argentina,42.3
2,2,2020-01-03,Argentina,0.0,104.0,0.0,5.0,31.9,11.198,7.441,...,2020,0.84,75.8921,17.87487,11.147269,19178.33184,ARG,8496.428157,Argentina,42.3
3,3,2020-01-04,Argentina,0.0,180.0,0.0,76.0,31.9,11.198,7.441,...,2020,0.84,75.8921,17.87487,11.147269,19178.33184,ARG,8496.428157,Argentina,42.3
4,4,2020-01-05,Argentina,0.0,194.0,0.0,14.0,31.9,11.198,7.441,...,2020,0.84,75.8921,17.87487,11.147269,19178.33184,ARG,8496.428157,Argentina,42.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21915,21915,2022-12-27,Venezuela,57.0,0.0,0.0,0.0,29.0,6.614,3.915,...,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21916,21916,2022-12-28,Venezuela,20.0,0.0,0.0,0.0,29.0,6.614,3.915,...,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21917,21917,2022-12-29,Venezuela,73.0,0.0,0.0,0.0,29.0,6.614,3.915,...,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21918,21918,2022-12-30,Venezuela,100.0,0.0,1.0,0.0,29.0,6.614,3.915,...,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21919,21919,2022-12-31,Venezuela,69.0,0.0,0.0,0.0,29.0,6.614,3.915,...,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_LAT_final.columns

Index(['Date', 'location', 'new_cases', 'total_tests', 'new_deaths',
       'new_tests', 'median_age', 'aged_65_older', 'aged_70_older',
       'population',
       ...
       'Year', 'hdi', 'le', 'eys', 'mys', 'gnipc', 'Country Code', 'PIB',
       'Country Name', 'Gini'],
      dtype='object', length=108)

Eliminando colunas que não se fazem mais necessárias

In [ ]:
df_LAT_final.drop([ "human_development_index", "location","Country Name", "Country Code"], axis=1, inplace=True)

In [ ]:
df_LAT_final.drop([ "life_expectancy"], axis=1, inplace=True)

Fazendo merge com outras tabelas

In [ ]:
df_LAT_final = pd.merge(df_LAT_final,df_diabetes, left_on=['CountryCode'], right_on=['Country Code'],how='left')
df_LAT_final = pd.merge(df_LAT_final,df_trabalho_informal_mod, left_on=['CountryName'], right_on=['ref_area.label'],how='left')
df_LAT_final = pd.merge(df_LAT_final,df_density_mod, left_on=['CountryCode'], right_on=['Country Code'],how='left')
df_LAT_final = pd.merge(df_LAT_final,df_hhSize, left_on=['CountryName'], right_on=['Country or area'],how='left')
df_LAT_final = pd.merge(df_LAT_final,df_hospital_density_mod, left_on=['CountryName'], right_on=['Location'],how='left')

In [ ]:
print(df_LAT_final.columns)

Index(['Date', 'new_cases', 'total_tests', 'new_deaths', 'new_tests',
       'median_age', 'aged_65_older', 'aged_70_older', 'population',
       'gdp_per_capita',
       ...
       'pct_informal_ag_jobs', 'pct_informal_n_ag_jobs',
       'pct_informal_tot_jobs', 'Country Name_y', 'Country Code_y',
       'Population Density', 'Country or area',
       'Average household size (number of members)', 'Location',
       'Hospital_Density_Per_100k'],
      dtype='object', length=117)

In [ ]:
df_LAT_final.drop(['Location','Country or area','Country Name_y','ref_area.label','Country Code_y','Country Code_x', 'Country Name_x'], axis=1, inplace=True)

In [ ]:
df_LAT_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21920 entries, 0 to 21919
Columns: 110 entries, Date to Hospital_Density_Per_100k
dtypes: datetime64[ns](1), float64(96), int64(2), object(11)
memory usage: 18.6+ MB

Exportando o dataset final como arquivo csv

In [ ]:
df_LAT_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21920 entries, 0 to 21919
Columns: 110 entries, Date to Hospital_Density_Per_100k
dtypes: datetime64[ns](1), float64(96), int64(2), object(11)
memory usage: 18.6+ MB

Rearranjando as colunas só pra ficar bonitinho

In [ ]:
nova_ordem_colunas=['Date', 'CountryName', 'CountryCode', 'RegionName', 'RegionCode', 'Jurisdiction', 'C1_School closing', 'C1_Flag', 'C2_Workplace closing', 'C2_Flag', 'C3_Cancel public events', 'C3_Flag', 'C4_Restrictions on gatherings', 'C4_Flag', 'C5_Close public transport', 'C5_Flag', 'C6_Stay at home requirements', 'C6_Flag', 'C7_Restrictions on internal movement', 'C7_Flag', 'C8_International travel controls', 'E1_Income support', 'E1_Flag', 'E2_Debt/contract relief', 'E3_Fiscal measures', 'E4_International support', 'H1_Public information campaigns', 'H1_Flag', 'H2_Testing policy', 'H3_Contact tracing', 'H4_Emergency investment in healthcare', 'H5_Investment in vaccines', 'H6_Facial Coverings', 'H6_Flag', 'H7_Vaccination policy', 'H7_Flag', 'H8_Protection of elderly people', 'H8_Flag', 'M1_Wildcard', 'V1_Vaccine Prioritisation (summary)', 'V2A_Vaccine Availability (summary)', 'V2B_Vaccine age eligibility/availability age floor (general population summary)', 'V2C_Vaccine age eligibility/availability age floor (at risk summary)', 'V2D_Medically/ clinically vulnerable (Non-elderly)', 'V2E_Education', 'V2F_Frontline workers  (non healthcare)', 'V2G_Frontline workers  (healthcare)', 'V3_Vaccine Financial Support (summary)', 'V4_Mandatory Vaccination (summary)', 'ConfirmedCases', 'ConfirmedDeaths', 'StringencyIndex', 'StringencyIndexForDisplay', 'StringencyLegacyIndex', 'StringencyLegacyIndexForDisplay', 'GovernmentResponseIndex', 'GovernmentResponseIndexForDisplay', 'ContainmentHealthIndex', 'ContainmentHealthIndexForDisplay', 'EconomicSupportIndex', 'EconomicSupportIndexForDisplay', 'Day', 'retail_and_recreation_percent_change_from_baseline', 'grocery_and_pharmacy_percent_change_from_baseline', 'parks_percent_change_from_baseline', 'transit_stations_percent_change_from_baseline', 'workplaces_percent_change_from_baseline', 'residential_percent_change_from_baseline', 'total_vaccinations', 'people_vaccinated', 'people_fully_vaccinated', 'total_boosters', 'new_vaccinations', 'new_vaccinations_smoothed', 'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred', 'total_boosters_per_hundred', 'new_vaccinations_smoothed_per_million', 'new_people_vaccinated_smoothed_per_hundred', 'new_cases', 'total_tests', 'new_deaths', 'new_tests', 'median_age', 'aged_65_older', 'aged_70_older', 'population', 'gdp_per_capita', 'extreme_poverty', 'hospital_beds_per_thousand', 'new_deaths_mm7', 'new_cases_mm7', 'country_region', 'sub_region_1', 'metro_area', 'Year', 'hdi', 'le', 'eys', 'mys', 'gnipc', 'PIB', 'Gini', 'Diabetes_Prevalence_2021', 'pct_informal_ag_jobs', 'pct_informal_n_ag_jobs', 'pct_informal_tot_jobs', 'Population Density', 'Average household size (number of members)', 'Hospital_Density_Per_100k']
df_LAT_final = df_LAT_final.loc[:, nova_ordem_colunas]

Povoando valores faltantes hdi, mys, gini

In [ ]:
df_val_fat = pd.read_excel('/content/povoando dados socioec.xlsx', header=0)

In [ ]:
# Realizar a junção (merge) dos datasets com base nas colunas de país e ano
df_LAT_final = pd.merge(df_LAT_final, df_val_fat, left_on=['CountryName', 'Year'],right_on=['CountryName', 'Ano'], how="left")

In [ ]:
# Remover a coluna de hdi_x do df_LAT_final, que contém os valores faltantes
df_LAT_final.drop(["hdi_x","mys_x","Gini_x","Ano"], axis=1, inplace=True)

# Renomear a coluna de hdi_y para hdi, que contém os valores completos do df_val_fat
df_LAT_final.rename(columns={"hdi_y": "hdi"}, inplace=True)
df_LAT_final.rename(columns={"mys_y": "mys"}, inplace=True)
df_LAT_final.rename(columns={"Gini_y": "gini"}, inplace=True)

# Resetar os índices do df_LAT_final
df_LAT_final.reset_index(drop=True, inplace=True)

In [ ]:
df_LAT_final[df_LAT_final['Ano']==2022]

,Date,CountryName,CountryCode,RegionName,RegionCode,Jurisdiction,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,...,pct_informal_ag_jobs,pct_informal_n_ag_jobs,pct_informal_tot_jobs,Population Density,Average household size (number of members),Hospital_Density_Per_100k,Ano,hdi,mys,gini
731,2022-01-01,Argentina,ARG,NaN,NaN,NAT_TOTAL,1.0,1.0,2.0,1.0,...,28.8,49.0,48.9,16.580893,2.95,NaN,2022,0.842,11.147269,42.0
732,2022-01-02,Argentina,ARG,NaN,NaN,NAT_TOTAL,1.0,1.0,2.0,1.0,...,28.8,49.0,48.9,16.580893,2.95,NaN,2022,0.842,11.147269,42.0
733,2022-01-03,Argentina,ARG,NaN,NaN,NAT_TOTAL,1.0,1.0,2.0,1.0,...,28.8,49.0,48.9,16.580893,2.95,NaN,2022,0.842,11.147269,42.0
734,2022-01-04,Argentina,ARG,NaN,NaN,NAT_TOTAL,1.0,1.0,2.0,1.0,...,28.8,49.0,48.9,16.580893,2.95,NaN,2022,0.842,11.147269,42.0
735,2022-01-05,Argentina,ARG,NaN,NaN,NAT_TOTAL,1.0,1.0,2.0,1.0,...,28.8,49.0,48.9,16.580893,2.95,NaN,2022,0.842,11.147269,42.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21915,2022-12-27,Venezuela,VEN,NaN,NaN,NAT_TOTAL,0.0,NaN,0.0,NaN,...,90.3,55.6,58.3,32.300270,4.33,NaN,2022,0.691,11.107277,43.8
21916,2022-12-28,Venezuela,VEN,NaN,NaN,NAT_TOTAL,0.0,NaN,0.0,NaN,...,90.3,55.6,58.3,32.300270,4.33,NaN,2022,0.691,11.107277,43.8
21917,2022-12-29,Venezuela,VEN,NaN,NaN,NAT_TOTAL,0.0,NaN,0.0,NaN,...,90.3,55.6,58.3,32.300270,4.33,NaN,2022,0.691,11.107277,43.8
21918,2022-12-30,Venezuela,VEN,NaN,NaN,NAT_TOTAL,0.0,NaN,0.0,NaN,...,90.3,55.6,58.3,32.300270,4.33,NaN,2022,0.691,11.107277,43.8
21919,2022-12-31,Venezuela,VEN,NaN,NaN,NAT_TOTAL,0.0,NaN,0.0,NaN,...,90.3,55.6,58.3,32.300270,4.33,NaN,2022,0.691,11.107277,43.8

In [ ]:
df_LAT_final.to_excel("Dataset Jessica v23.xlsx")